{% set version = "1.2.0" %}

package:
    name: virchip
    version: {{ version }}

source:
    url: https://bitbucket.org/hoffmanlab/virchip/src/default/get/v{{ version }}.tar.gz
    md5sum: 6dd38652bbb75bc2584b38ee5b2b6852
    sha256: 69a9095829f00839b0dcff80fc62b735582419632095ba27693e8217ffe5cddf

build:
    number: 0


requirements:
    run:
        - python >= 2.7.11, < 3
        - pandas >= 0.23.1, < 0.24.0
        - numpy >= 1.4.15
        - scikit-lean >= 0.18.1, < 0.19.0
        - scipy >= 1.1.0, < 1.2.0
        - r-base

    test:
        commands:
            - bash test_run.sh $PWD

    about:
        home: https://virchip.hoffmanlab.org
        license: General Public License version 3
        summary: "Virtual ChIP-seq predicts transcription factor binding in any cell type with chromatin accessibility and transcriptome data. Manuscript DOI: https://doi.org/10.1101/168419"
